#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

redirect_cmd() {
    if [[ "${DEBUG}" == "yes" ]]; then
        "$@" -vv
    else
        "$@" > /dev/null 2>&1
    fi
}

redirect_cmd exec s6-setuidgid hotio "${APP_DIR}/trackarr" --config-dir="${CONFIG_DIR}/app"
